import Notes from '@/Shared/Components/Notes/Notes';
import React from 'react';
import MultipleDefContent from '../../Components/MultipleDefContent';

const WhatIsAuth: React.FC = () => {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
      <MultipleDefContent
        contents={[
          {
            title: 'What is Authentication?',
            content: (
              <Notes
                notes={[
                  {
                    note: 'Authentication is the process of verifying the identity of a user, device, or any other entity attempting to access a system or resource.',
                    subNotes: [
                      {
                        note: '"Are you who you say you are?',
                      },
                    ],
                  },
                ]}
                specialNotes
              />
            ),
          },
          {
            title: 'Authentication Factors',
            content: (
              <>
                <p>
                  Authentication factors are different categories of credentials used to verify a
                  user`s identity. These factors are often categorized into three main type:
                </p>
                <Notes
                  notes={[
                    {
                      note: 'Something you know: This is the most common factor and includes passwords, PINs, security questions, and passphrases',
                      subNotes: [
                        {
                          note: 'Example: Entering your password to log into your email account.',
                        },
                        {
                          note: 'Vulnerability: Susceptible to phishing, brute-force attacks, and social engineering.',
                        },
                      ],
                    },
                    {
                      note: 'Something you have: This factor involves a physical token or device that the user possesses, such as a security token, a smart card, or a one-time password (OTP) generated by a mobile app.',
                      subNotes: [
                        {
                          note: 'Example: Using a security token to generate a code for logging into a bank account.',
                        },
                        {
                          note: 'Vulnerability: Can be lost, stolen, or cloned.',
                        },
                      ],
                    },
                    {
                      note: 'Something you are: This factor relies on biometric data, such as fingerprints, facial recognition, voice recognition, or iris scans.',
                      subNotes: [
                        {
                          note: 'Example: Using your fingerprint to unlock your smartphone.',
                        },
                        {
                          note: 'Vulnerability: Can be spoofed or compromised, and raises privacy concerns.',
                        },
                      ],
                    },
                    {
                      note: 'Using multiple factors, known as multi-factor authentication (MFA), significantly enhances security by requiring users to provide credentials from different categories',
                    },
                  ]}
                  specialNotes
                />
              </>
            ),
          },
          {
            title: 'Types of Authentication',
            content: (
              <>
                <Notes
                  notes={[
                    {
                      note: 'Password-Based Authentication: The most traditional method, relying on usernames and passwords.',
                    },
                    {
                      note: 'Token-Based Authentication: Uses tokens (like JWTs) to verify identity after initial login.',
                    },
                    {
                      note: 'Multi-Factor Authentication (MFA): As discussed, uses multiple authentication factors for increased security.',
                    },
                    {
                      note: 'Social Authentication (OAuth 2.0): Allows users to log in using existing accounts from social media platforms like Google or Facebook.',
                    },
                  ]}
                  specialNotes
                />
              </>
            ),
          },
        ]}
      />
    </div>
  );
};

WhatIsAuth.displayName = 'WhatIsAuth';

export default WhatIsAuth;
